spring.application.name=PROD:Spring JPA Investigation

spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.url=jdbc:sqlite:C:\\work\\training\\java\\users_production.db

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

pt.data.titlexxxxx=PROD:Professional Training Ltd.